# Use Node.js LTS version
FROM node:22.1.0-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package files first
COPY package.json package-lock.json ./

# Copy local node_modules (already installed on host)
COPY node_modules/ ./node_modules/

# Copy the rest of your application
COPY . .

# Expose Angular's dev server port
EXPOSE 4200

# Start Angular dev server
CMD ["npm", "start"]
